import Link from 'next/link';
import type { Metadata } from 'next';
import { BrandLogo } from '@/components/layout/brand-logo';
import { SiteHeader } from '@/components/layout/site-header';

export const metadata: Metadata = {
  title: 'Terms & Conditions — Wellderly Wayfinder',
  description:
    'Please review these terms carefully before using Wellderly Wayfinder.',
};

const LAST_UPDATED = 'April 1, 2026';

type Section = {
  id: string;
  title: string;
  body: React.ReactNode;
};

const SECTIONS: Section[] = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    body: (
      <>
        <p>
          By accessing or using Wellderly Wayfinder (&ldquo;Wellderly,&rdquo;
          &ldquo;we,&rdquo; or &ldquo;us&rdquo;), you agree to be bound by these
          Terms &amp; Conditions and our Privacy Notice. If you do not agree
          with any portion of these terms, please do not use the Service.
        </p>
        <p>
          These terms apply to everyone who uses Wellderly, including family
          members, caregivers, and professionals supporting an older adult.
        </p>
      </>
    ),
  },
  {
    id: 'use-of-services',
    title: 'Use of Services',
    body: (
      <>
        <p>
          Wellderly provides educational information, tailored recommendations,
          and care planning guidance to help families navigate aging-related
          decisions. The Service is intended for informational and planning
          purposes and does not replace medical, legal, or financial advice
          from a qualified professional.
        </p>
        <p>
          You may use the Service only in compliance with applicable laws and
          these terms. You may not use the Service to harm others, misrepresent
          your identity, or interfere with the normal operation of the
          platform.
        </p>
      </>
    ),
  },
  {
    id: 'user-responsibilities',
    title: 'User Responsibilities',
    body: (
      <>
        <p>
          You are responsible for the accuracy of the information you provide
          and for decisions you make based on recommendations generated by the
          Service. You agree to keep your account credentials confidential and
          to notify us if you suspect unauthorized access to your account.
        </p>
        <ul>
          <li>Provide accurate, current, and complete information.</li>
          <li>
            Only share personal or medical information about others if you are
            authorized to do so.
          </li>
          <li>Use Wellderly in good faith on behalf of the person you support.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'privacy-and-data',
    title: 'Privacy and Data Use',
    body: (
      <>
        <p>
          Your information is handled in accordance with our Privacy Notice.
          Wellderly does not sell personal data, and we do not accept
          sponsorships or referral fees from providers that would influence the
          recommendations we generate.
        </p>
        <p>
          Care plans and related information are private by default. You may
          choose to share a plan with family, caregivers, or providers at your
          discretion.
        </p>
      </>
    ),
  },
  {
    id: 'payments',
    title: 'Payments and Subscriptions',
    body: (
      <>
        <p>
          Certain Wellderly features may require a paid subscription or
          one-time purchase. Prices, billing cycles, and cancellation terms
          will be clearly disclosed before checkout. Subscriptions renew
          automatically unless cancelled in accordance with the terms disclosed
          at purchase.
        </p>
        <p>
          Refunds, where offered, are processed according to the policy
          presented at the time of purchase. Taxes may apply depending on your
          location.
        </p>
      </>
    ),
  },
  {
    id: 'intellectual-property',
    title: 'Intellectual Property',
    body: (
      <>
        <p>
          Wellderly, including its name, logo, content, software, and all
          materials provided through the Service, is the property of Wellderly
          Wayfinder or its licensors. You are granted a limited, non-exclusive
          license to use the Service for personal, non-commercial purposes.
        </p>
        <p>
          You may not copy, modify, distribute, or create derivative works from
          our materials without prior written permission, except as permitted
          by applicable law.
        </p>
      </>
    ),
  },
  {
    id: 'disclaimers',
    title: 'Disclaimers',
    body: (
      <>
        <p>
          Wellderly is provided on an &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; basis. We do our best to provide accurate and
          helpful recommendations, but we do not guarantee any specific
          outcomes. Information provided through the Service is not medical,
          legal, tax, or financial advice.
        </p>
        <p>
          Always consult a qualified professional about your specific
          situation, particularly for medical, legal, or financial decisions.
        </p>
      </>
    ),
  },
  {
    id: 'limitation-of-liability',
    title: 'Limitation of Liability',
    body: (
      <>
        <p>
          To the fullest extent permitted by applicable law, Wellderly and its
          affiliates will not be liable for indirect, incidental, consequential,
          or punitive damages arising from your use of the Service.
        </p>
        <p>
          Nothing in these terms limits liability that cannot be limited under
          applicable law, including liability for gross negligence or willful
          misconduct.
        </p>
      </>
    ),
  },
  {
    id: 'changes-to-terms',
    title: 'Changes to These Terms',
    body: (
      <>
        <p>
          We may update these terms from time to time. When we do, we will
          update the &ldquo;Last updated&rdquo; date above and, where
          appropriate, provide additional notice. Continued use of the Service
          after changes take effect constitutes acceptance of the revised
          terms.
        </p>
      </>
    ),
  },
  {
    id: 'contact',
    title: 'Contact Information',
    body: (
      <>
        <p>
          Questions about these terms? We&rsquo;re happy to help. Reach us at{' '}
          <Link
            href="mailto:hello@wellderly.com"
            className="font-semibold text-navy underline decoration-coral/60 underline-offset-4 transition hover:decoration-coral"
          >
            hello@wellderly.com
          </Link>
          .
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <>
      <SiteHeader variant="marketing" />
      <main id="content" className="bg-white">
        {/* Page intro — text-only, calm legal tone */}
        <section
          className="border-b border-line/45 bg-[#F7F6F4] px-4 py-20 sm:px-6 sm:py-24 lg:px-10 lg:py-28"
          aria-labelledby="terms-heading"
        >
          <div className="mx-auto w-full max-w-content">
            <div className="max-w-2xl">
              <p className="text-[0.625rem] font-semibold uppercase tracking-[0.18em] text-navy/45 sm:text-[0.6875rem]">
                Legal
              </p>
              <h1
                id="terms-heading"
                className="mt-6 text-[1.875rem] font-semibold leading-[1.12] tracking-tight text-navy sm:mt-7 sm:text-[2.125rem] lg:text-[2.375rem]"
              >
                Terms &amp; Conditions
              </h1>
              <p className="mt-7 max-w-prose text-[0.9375rem] leading-[1.76] text-navy/72 sm:mt-8 sm:text-base sm:leading-[1.78]">
                Please review these terms carefully before using Wellderly
                Wayfinder. They explain how our Service works and the
                responsibilities we share.
              </p>
              <div className="mt-10 flex items-center gap-3 sm:mt-12">
                <span
                  aria-hidden="true"
                  className="h-px w-8 bg-navy/20"
                />
                <p className="text-[0.75rem] uppercase tracking-[0.16em] text-navy/45 sm:text-[0.8125rem] sm:tracking-[0.14em]">
                  Last updated · {LAST_UPDATED}
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="px-4 py-14 sm:px-6 sm:py-20 lg:px-10 lg:py-24">
          <div className="mx-auto grid w-full max-w-content grid-cols-1 gap-12 lg:grid-cols-[minmax(0,13rem)_minmax(0,1fr)] lg:gap-16">
            {/* Table of contents */}
            <aside
              aria-labelledby="toc-heading"
              className="order-first lg:order-none"
            >
              {/* Mobile: collapsible */}
              <details className="group rounded-card border border-line/55 bg-[#F7F6F4] px-4 py-3 lg:hidden">
                <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-[0.8125rem] font-semibold uppercase tracking-[0.14em] text-navy/70 [&::-webkit-details-marker]:hidden">
                  <span id="toc-heading">On this page</span>
                  <span
                    aria-hidden="true"
                    className="text-navy/50 transition-transform duration-200 group-open:rotate-180"
                  >
                    ▾
                  </span>
                </summary>
                <nav className="mt-3" aria-label="Terms sections">
                  <ol className="flex flex-col gap-2 text-[0.875rem] leading-[1.5] text-navy/75">
                    {SECTIONS.map((section, idx) => (
                      <li key={section.id}>
                        <Link
                          href={`#${section.id}`}
                          className="flex gap-2.5 rounded-sm py-0.5 transition hover:text-navy focus:outline-none focus-visible:text-navy focus-visible:underline"
                        >
                          <span className="w-5 shrink-0 text-navy/40">
                            {String(idx + 1).padStart(2, '0')}
                          </span>
                          <span>{section.title}</span>
                        </Link>
                      </li>
                    ))}
                  </ol>
                </nav>
              </details>

              {/* Desktop: sticky list */}
              <nav
                aria-label="Terms sections"
                className="hidden lg:sticky lg:top-28 lg:block"
              >
                <p className="text-[0.6875rem] font-semibold uppercase tracking-[0.16em] text-navy/45">
                  On this page
                </p>
                <ol className="mt-4 flex flex-col gap-2.5 border-l border-line/70 pl-4 text-[0.875rem] leading-[1.45] text-navy/70">
                  {SECTIONS.map((section, idx) => (
                    <li key={section.id}>
                      <Link
                        href={`#${section.id}`}
                        className="group inline-flex gap-2.5 transition hover:text-navy focus:outline-none focus-visible:text-navy focus-visible:underline"
                      >
                        <span className="w-5 shrink-0 text-navy/40 group-hover:text-navy/60">
                          {String(idx + 1).padStart(2, '0')}
                        </span>
                        <span>{section.title}</span>
                      </Link>
                    </li>
                  ))}
                </ol>
              </nav>
            </aside>

            {/* Main reading column */}
            <article className="min-w-0 max-w-[42rem]">
              <p className="text-[0.9375rem] leading-[1.74] text-navy/72 sm:text-base sm:leading-[1.76]">
                These Terms &amp; Conditions govern your use of Wellderly
                Wayfinder. Together with our Privacy Notice, they form the
                agreement between you and Wellderly.
              </p>

              <div className="mt-12 divide-y divide-line/50 [&>section]:py-10 first:[&>section]:pt-0 last:[&>section]:pb-0 sm:[&>section]:py-12">
                {SECTIONS.map((section, idx) => (
                  <section
                    key={section.id}
                    id={section.id}
                    aria-labelledby={`${section.id}-heading`}
                    className="scroll-mt-28"
                  >
                    <div className="flex items-baseline gap-3">
                      <span
                        aria-hidden="true"
                        className="text-[0.75rem] font-semibold uppercase tracking-[0.16em] text-navy/40"
                      >
                        {String(idx + 1).padStart(2, '0')}
                      </span>
                      <h2
                        id={`${section.id}-heading`}
                        className="text-[1.125rem] font-semibold leading-[1.3] tracking-tight text-navy sm:text-[1.25rem]"
                      >
                        {section.title}
                      </h2>
                    </div>
                    <div className="mt-5 space-y-4 text-[0.9375rem] leading-[1.76] text-navy/82 [&_a]:font-semibold [&_a]:text-navy [&_a]:underline [&_a]:decoration-coral/50 [&_a]:underline-offset-4 hover:[&_a]:decoration-coral [&_li]:leading-[1.7] [&_p]:max-w-prose [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-5 sm:text-base sm:leading-[1.78]">
                      {section.body}
                    </div>
                  </section>
                ))}
              </div>

              <div className="mt-16 rounded-card border border-line/55 bg-[#F7F6F4] px-5 py-5 sm:px-6 sm:py-6">
                <p className="text-[0.8125rem] leading-[1.7] text-navy/65 sm:text-[0.875rem] sm:leading-[1.72]">
                  Have questions or need a human?{' '}
                  <Link
                    href="mailto:hello@wellderly.com"
                    className="font-semibold text-navy underline decoration-coral/55 underline-offset-4 transition hover:decoration-coral"
                  >
                    hello@wellderly.com
                  </Link>
                  . A real person will respond.
                </p>
              </div>

              <p className="mt-10">
                <Link
                  href="/"
                  className="inline-flex items-center gap-2 text-[0.875rem] font-semibold text-navy/75 transition hover:text-navy focus:outline-none focus-visible:text-navy focus-visible:underline"
                >
                  <span aria-hidden="true">←</span>
                  Return to Wellderly
                </Link>
              </p>
            </article>
          </div>
        </section>
      </main>

      <footer
        className="border-t border-line/50 bg-white px-4 py-8 sm:px-6 sm:py-10 lg:px-10"
        role="contentinfo"
      >
        <div className="mx-auto flex w-full max-w-content flex-col items-start gap-5 text-sm text-navy/65 sm:flex-row sm:items-center sm:justify-between">
          <Link
            href="/"
            className="inline-block rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-coral focus-visible:ring-offset-2"
            aria-label="Wellderly home"
          >
            <BrandLogo alt="Wellderly" />
          </Link>
          <p className="text-[0.8125rem] leading-[1.6] text-navy/55">
            © 2026 Wellderly Wayfinder · Proprietary &amp; Confidential
          </p>
        </div>
      </footer>
    </>
  );
}
